trainer:
  max_epochs: 22
  check_val_every_n_epoch: 1
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "avs"
      name: "vpo_ss_ease_dinov2_large_512_sig"
model:
  class_path: training.mask_classification_s4.MaskClassificationS4
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [2589, 4315, 6041, 7767]
    attn_mask_annealing_end_steps: [4315, 6041, 7767, 9493]
    network:
      class_path: models.ease_vit.EASEViT
      init_args:
        num_q: 100
        rope_seq_len: 5
        early_fusion: True
        encoder:
          class_path: models.encoders.vit.ViT
        query_generator:
          class_path: models.query_generators.attention_generator.AttentionGenerator
          init_args:
            num_layers: 4
            embed_dim: 1024
            project_input_dim: 1024
            project_input: False
        feat_upscaler:
          class_path: models.feat_upscalers.conv_scaler.ConvScaler
          init_args:
            encoder_patch_size: [16, 16]
        audio_proj:
          class_path: torch.nn.Linear
          init_args:
            in_features: 128
            out_features: 1024
        fuser:
          class_path: models.fusers.bi_attention.BiAttentionFuser
          init_args:
            vision_dim: 1024
            audio_dim: 1024
            embed_dim: 1024
            audio_token_num: 1  # for late this is num_q
            use_sigmoid: True
data:
  class_path: datasets.vpo_ss.VPOSS
  init_args:
    read_per_frame: False
    img_size: [512, 512]
    num_classes: 2
    batch_size: 2
    neg_audio_p: 0.0
    vggish_emb_fn: vggish_emb.pt
    use_robust_for_testing_if_available: False
